#!/bin/sh
# You need c-coderdbc tool build in your environment
# Path to c-coderdbc binary: 
# (https://gitlab.com/solar-boat-pwr/software.tools.c-coderdbc)
coderdbc_path=../software.tools.c-coderdbc/build/coderdbc

# You also need to enter DBC file path: 
# (https://gitlab.com/solar-boat-pwr/miscellaneous.can-ids)
dbc_path=../miscellaneous.can-ids/SBT.dbc

mkdir generated_code
$coderdbc_path -dbc $dbc_path -out generated_code -drvname CanParser -rw

mv generated_code/CanParser_autogenerated.cpp CanParser_autogenerated.cpp
mv generated_code/CanParser_autogenerated.hpp CanParser_autogenerated.hpp

clang-format-12 -i --style=file CanParser_autogenerated.cpp CanParser_autogenerated.hpp

rm -rf generated_code
