#/bin/sh
# You need c-coderdbc tool build in your environment
# Path to c-coderdbc binary: 
# (https://gitlab.com/solar-boat-pwr/software.tools.c-coderdbc)
coderdbc_path=../software.tools.c-coderdbc/build/coderdbc

# You also need to enter DBC file path: 
# (https://gitlab.com/solar-boat-pwr/miscellaneous.can-ids)
dbc_path=../miscellaneous.can-ids/SBT-generic.dbc

# .json file path is mandatory:
# (https://gitlab.com/solar-boat-pwr/miscellaneous.can-ids)
json_path=../miscellaneous.can-ids/can-IDs.json

mkdir generated_code
$coderdbc_path -dbc $dbc_path -out generated_code -drvname CanParser -rw

python3 runScript.py --json_file $json_path --dbc_file $dbc_path --schema canIDsSchema.json  --python_header CanID_autogenerated.py --SDK_header CanID_autogenerated.hpp

mv generated_code/CanParser_autogenerated.cpp CanParser_autogenerated.cpp
mv generated_code/CanParser_autogenerated.hpp CanParser_autogenerated.hpp

clang-format-12 -i --style=file CanParser_autogenerated.cpp CanParser_autogenerated.hpp CanID_autogenerated.hpp


rm -rf generated_code